trigger:
  - master

pool:
  name: 'COMP367-Windows'  # Your self-hosted agent pool

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  nugetFeed: 'Lab04'  

steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: NuGetCommand@2
    displayName: 'Pack NuGet Package'
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      packDestination: '$(Build.ArtifactStagingDirectory)'

  - task: NuGetCommand@2
    displayName: 'Push to Azure Artifacts'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '$(nugetFeed)'
